EVapp/__init__.py
from flask import Flask 
from .extensions import db, socketio
from .routes import main 


def create_app():
    app = Flask(__name__)
    app.config["DEBUG"] = True
    app.config["SECRET_KEY"] = "secret"

    # Configuring the Flask app to connect to the MySQL database
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://myuser:#edge_dev#@localhost/EV'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    app.register_blueprint(main)

    socketio.init_app(app)
    db.init_app(app)

    return app

EVapp/routes.py
from flask import Blueprint, render_template
from flask import *
import subprocess
import threading
import os
from .services import *

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render_template("index.html")

@main.route("/map")
def mapTest():
    return render_template("map.html") 

# @main.route("/chat")
# def chat():
#     return render_template("chat.html")

# @main.route("/public")
# def public():
#     return render_template("public.html")

@main.route("/CSs")
def CSList():
    return render_template("stations.html", CSList = CSList)

@main.route("/api/CS")
def sendCS():
    stations = readCS()
    data = [{"id": s.id, "name": s.name, "location": s.location, "lat": s.lat, "lng": s.lng, "status": s.status} for s in stations]
    return jsonify(data)


@main.route("/parking")
def parking():
    return render_template("parkings.html")

@main.route("/CSs/<port_type>")
def portType(port_type):
    return render_template("chat.html", port=port_type)

@main.route("/CSReq")
def CSRequest():
    return render_template("chargeReq.html")

ocpp_started = False

def run_ocpp_server():
    subprocess.Popen(
        ["python3", os.path.join(os.path.dirname(__file__), "server.py")],
        stdout=None, stderr=None
    )

def run_ocpp_client():
    subprocess.Popen(
        ["python3", os.path.join(os.path.dirname(__file__), "client.py")],
        stdout=None, stderr=None
    )

@main.route("/charging")
def charging():
    global ocpp_started
    port = request.args.get("port")

    if not ocpp_started:
        threading.Thread(target=run_ocpp_server, daemon=True).start()
        threading.Thread(target=run_ocpp_client, daemon=True).start()
        ocpp_started = True

    return render_template("charging.html", port=port)

EVapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="/static/js/evId.js"></script>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet">
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdn.socket.io/4.6.0/socket.io.min.js"></script>
        <title>{% block title %}EV{% endblock %}</title>
        {% block styles %}
        <style>
        #header {
            height: 135px;
        }
    </style>
        {% endblock %}

    </head>

    <body>
        <div style="height: 6rem;"></div>
        <div
            class="container-fluid row justify-content-center align-content-center mx-auto d-flex flex-column">
            <div class="p-4 shadow-lg" id="container"
                style="width: 52rem; height: 560px; border-radius: 25px; background-color: rgb(206, 231, 245);">

                {% block content %}{% endblock %}

                <div
                    class="col justify-content-center text-center align-content-center">
                    <a href="/"><img src="/static/images/home.png" alt="Home"
                            style="width:40px;" /></a>
                    <a href="{{ url_for('main.CSList') }}"><img src="/static/images/cs.png"
                            alt="Stations" style="width:30px;" /></a>
                    <a href="{{ url_for('main.CSRequest') }}" id="ChargeReq">
                        <img src="/static/images/ev.png" alt="ChargeRequest"
                            class="img-fluid" style="width:30px;" />
                    </a>
                </div>
            </div>
        </div>

        <script src="/static/js/evId.js"></script>
        <script>
        const evId = getEVId();

        const socket = io({
            auth: {
                evID: evId
            }
        });

    </script>

        {% block scripts %}{% endblock %}

    </body>

</html>

EVapp/templates/chargeReq.html
{% extends 'base.html' %}
{% block title %}Charge Request{% endblock %}
{% block styles %}
<style>
    #header {
        height: 120px;
    }

    #mainContainer {
        height: 350px;
        padding-right: 10px;
    }

    .card {
        border-radius: 12px;
    }
</style>
{% endblock %}

{% block content %}
<div id="header">
    <h2 class="text-center m-1">Charge Request</h2>
</div>
<div class="p-4 mt-2 text-center" id="mainContainer">
    <div id="chargeVal" class="row row-cols-3 g-5"></div>
</div>

{% endblock %}

{% block scripts %}
<script>
    const chargeLevels = [5, 10, 15, 20, 25, 30, 35, 40, 45];
    const buttonContainer = document.getElementById('chargeVal');

    chargeLevels.forEach(level => {
        const col = document.createElement('div');
        col.className = 'col';

        const button = document.createElement('button');
        button.className = 'btn btn-lg btn-light w-100 charge-btn';
        button.textContent = level + `%`;
        button.onclick = () => {
            socket.emit("chargeReq", level);
            alert(`Requesting ${level}% charge from nearby EVs...`);
        };

        col.appendChild(button);
        buttonContainer.appendChild(col);
    });


</script>
{% endblock %}

EVapp/templates/charging.html
{% extends 'base.html' %}
{% block title %}Charging{% endblock %}
{% block styles %}
<style>
    #header {
        height: 120px;
    }

    #scroll-container {
        height: 350px;
        padding-right: 10px;
    }

</style>
{% endblock %}
{% block content %}
<div id="header">
    <h2 id="csName" class="m-3 text-center"></h2>
</div>
<div class="col d-flex flex-column align-items-center text-center" id="scroll-container">
    <div class="card p-3 shadow-sm rounded" style="border: transparent; height: 60px;">
        <p>{{ port }}</p>
        <img src="/static/images/charging.png" 
             class="rounded mx-auto d-block m-3 pt-5 mt-3" 
             style="width: 25%;" />
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="/static/js/evId.js"></script>
<script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4hZAYtF1aoCvpBx6LM3-hgRlgCRAOszg&callback=console.debug&libraries=maps,marker&v=beta">
    </script>
<script>
        
        socket.emit("AutoCS", {
            position: [10, 14]
        })
    
    socket.on("route_result", (data) => {
        document.getElementById("csName").innerHTML = data.station_name;
        });
</script>
{% endblock %}

EVapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>
        <script src="https://cdn.socket.io/4.6.0/socket.io.min.js"
            integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
            crossorigin="anonymous"></script>

        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous">

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous">
        </script>
        <script src="/static/js/evId.js"></script>
    </head>

    <body>
        <div style="height: 6rem;"></div>
        <div
            class="container-fluid row justify-content-center align-content-center mx-auto">
            <div class="p-4 shadow-lg"
                style="width: 52rem; height: 550px; border-radius: 25px; border-color: transparent; background-color: rgb(206, 231, 245);">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <a href="#"><img src="/static/images/notif.png"
                                alt="EV Image" class="img-fluid"
                                style="height: 50px;">
                        </a>
                    </div>
                    <div class="col text-center">
                        <h2 class="m-0 me-5">Dashboard</h2>
                    </div>
                </div>
                <div class="col-6 mx-auto mt-5 pt-3 pb-2 text-center">
                    <p>Battery 68% (240 Km remaining)</p>
                    <p>105 Km</p>
                    <p>32 mins to destination</p>
                </div>
                <div id="chargeToast"
                    class="toast position-fixed top-50 start-50 translate-middle"
                    role="alert"
                    aria-live="assertive" aria-atomic="true"
                    data-bs-autohide="true" data-bs-delay="10000"
                    style="z-index: 2000; min-width: 300px; ">
                    <div class="toast-body text-center">
                    </div>
                </div>

                <div class="d-grid gap-2 col-6 mx-auto mt-5">
                    <div
                        class="border border-opacity-10 border-dark rounded-3 row p-1 text-center"
                        style="height: 70px;">
                        <a href="{{ url_for('main.CSList') }}"
                            class="btn btn-dark col m-1"
                            role="button">Charging
                            Stations</a>
                        <a href="{{ url_for('main.CSRequest') }}"
                            class="btn btn-primary col m-1"
                            role="button">Request
                            Charge</a>
                    </div>
                    <a href="{{ url_for('main.parking') }}"
                        class="btn btn-dark col m-1" style="height: 46px;"
                        role="button">Park</a>
                </div>
            </div>
        </div>

        <script>
        const evId = getEVId();

        const socket = io({
            auth: {
                evID: evId
            }
        });


        socket.on("ChargeReqAlert", function (value) {
            const toastBody = document.querySelector('#chargeToast .toast-body');
            toastBody.style.visibility = "visible";
            toastBody.innerHTML = `
        <strong>Nearby EV Requested ${value}% Charge</strong>
        <div class="mt-2 pt-2 border-top">
            <button type="button" class="btn btn-primary btn-sm">Accept</button>
            <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="toast">Close</button>
        </div>
    `;
            const toastElement = document.getElementById('chargeToast');
            const toast = new bootstrap.Toast(toastElement);
            toast.show();
        })

    </script>

    </body>

</html>

EVapp/templates/map.html
<!DOCTYPE html>
<html>
  <head>
    <title>bp pulse Charging Station</title>
    <!-- The callback parameter is required, so we use console.debug as a noop -->
    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4hZAYtF1aoCvpBx6LM3-hgRlgCRAOszg&callback=console.debug&libraries=maps,marker&v=beta">
    </script>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      gmp-map {
        height: 100%;
      }

      /* Optional: Makes the sample page fill the window. */
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <gmp-map center="51.925533294677734,0.8985742330551147" zoom="14" map-id="DEMO_MAP_ID">
      <gmp-advanced-marker position="51.925533294677734,0.8985742330551147" title="My location"></gmp-advanced-marker>
    </gmp-map>
  </body>
</html>

EVapp/templates/oldTemp/CSList.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Available CSs</title>

    <style>
        #header {
            height: 135px;
        }

        #scroll-container {
            height: 290px;
            overflow-y: auto;
            padding-right: 10px;
        }

        .card {
            border-radius: 12px;
            /* fixed typo */
        }

        #scroll-container::-webkit-scrollbar {
            width: 6px;
        }

        #scroll-container::-webkit-scrollbar-thumb {
            background-color: rgba(0, 0, 0, 0.2);
            border-radius: 10px;
        }
    </style>

    <script src="https://cdn.socket.io/4.6.0/socket.io.min.js"
        integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
        crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="/static/js/evId.js"></script>

</head>

<body>
    <div style="height: 6rem;"></div>
    <div class="container-fluid row justify-content-center align-content-center mx-auto d-flex flex-column">
        <div class="p-4 shadow-lg" id="container"
            style="width: 38rem; height: 500px; border-radius: 25px; background-color: rgb(206, 231, 245);">
            <div id="header">
                <div class="row">
                    <h2 class="mt-3 mb-4 text-center">Available Charging Stations</h2>
                </div>
                <div class="row justify-content-center mb-3">
                    <div class="col-auto">
                        <button id="auto" type="button" class="btn btn-dark px-4">Closest Station</button>
                    </div>
                </div>
            </div>
 
            <div class="row" id="scroll-container">
                <div id="cs-list" class="px-2">
                    <p>Loading stations...</p>
                </div>
            </div>
            <div class="col mt-1 justify-content-center text-center align-content-center">
                <a href="/">
                    <img src="/static/images/home.png" alt="Home" class="img-fluid" style="width:40px;" />
                </a>
                <a href="#" id="ChargeReq">
                    <img src="/static/images/ev.png" alt="ChargeRequest" class="img-fluid" style="width:30px;" />
                </a>
            </div>

        </div>
    </div>

    <script>
        const evId = getEVId();

        const socket = io({
            auth: {
                evID: evId
            }
        });

        document.getElementById("ChargeReq").addEventListener("click", function () {
            window.location.href = `/CSReq/${evId}`;
        });


        async function loadStations() {
            const response = await fetch("/static/data/CSList.json");
            const stations = await response.json();
            renderStations(stations);
        }

        function renderStations(stations) {
            const listContainer = document.getElementById("cs-list");
            listContainer.innerHTML = "";

            stations.forEach(station => {
                if (station.status === "Available") {
                    const row = document.createElement("div");
                    row.className = "row mb-3";

                    const a = document.createElement("a");
                    a.href = `/CSs/${station.id}`;
                    a.className = "text-decoration-none text-dark";

                    const card = document.createElement("div");
                    card.className = "card p-3 shadow-sm bg-body rounded";
                    card.style.borderColor = "transparent";
                    card.innerHTML = `
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <h5 class="mb-1">${station.name}</h5>
                                <p class="mb-1">📍 ${station.location} | ${station.distance_km} km away</p>
                                <p class="mb-0">Available Ports: ${station.available_ports}</p>
                            </div>
                        </div>
                    `;

                    a.appendChild(card);
                    row.appendChild(a);
                    listContainer.appendChild(row);
                }
            });
        }

        document.getElementById("auto").addEventListener("click", () => {
            socket.emit("AutoCS", {
                position: [10, 14]
            });
        });

        socket.on("route_result", (data) => {
            const listContainer = document.getElementById("cs-list");
            listContainer.innerHTML = "";

            if (data.error) {
                listContainer.innerHTML = `<p class="text-danger">${data.error}</p>`;
                return;
            }

            const row = document.createElement("div");
            row.className = "row mb-3 m-0";

            const card = document.createElement("div");
            card.className = "card p-3 shadow-sm bg-body rounded";
            card.style.borderColor = "transparent";

            let portsHTML = "";
            data.ports.forEach(port => {
                portsHTML += `
                <a href="#" class="text-decoration-none m-1 portData" portType="${port.type}" style="margin:0px 15px">
                <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">                    
                    <div class="col d-flex justify-content-between">
                        ${port.type} · ${port.power_kW} kW
                        <span class="badge bg-primary ">${port.available}/${port.total}</span>
                    </div>
                    </li>
                </ul>
                </div>
                </a>
            `;
            });

            card.innerHTML = `
                <div class="justify-content-between align-items-center text-center d-flex row" id="ClosestCS">
                    <div class="row p-0 m-0">
                        <h5 class="mb-3">${data.station_name} | 📍 ${data.station_distance} km Or ${data.path.length} steps away</h5>
                    </div>
                    <div class="d-flex justify-content-around flex-column" id="cs">
                        ${portsHTML}
                    </div>
                    <div class="d-flex justify-content-around flex-column mt-3">
                        <div class="card">
                            Map
                        </div>
                    </div>
                </div>
            `;

            const portLinks = card.querySelectorAll(".portData");
            portLinks.forEach(link => {
                link.addEventListener("click", (e) => {
                    e.preventDefault();
                    const portType = link.getAttribute("portType");
                    alert(`The ${portType} port is booked`);
                });
            });

            row.appendChild(card);
            listContainer.appendChild(row);

        });

        document.addEventListener("DOMContentLoaded", loadStations);
    </script>
</body>

</html>

EVapp/templates/oldTemp/CSReq.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Charge Req</title>

    <style>
        #header {
            height: 135px;
        }

        #mainContainer {
            height: 290px;
            padding-right: 10px;
        }

        .card {
            border-radius: 12px;
            /* fixed typo */
        }
    </style>

    <script src="https://cdn.socket.io/4.6.0/socket.io.min.js"
        integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
        crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</head>

<body>
    <div style="height: 6rem;"></div>
    <div class="container-fluid row justify-content-center align-content-center mx-auto d-flex flex-column">
        <div class="p-4 shadow-lg" id="container"
            style="width: 38rem; height: 500px; border-radius: 25px; background-color: rgb(206, 231, 245);">
            <div class="row">
                <h2 class="mt-3 mb-4 text-center">Charge Request</h2>
            </div>
            <div class="p-4 text-center mt-3" id="mainContainer">
                <div class="row p-3">
                    <button class="btn btn-lg btn-light col m-2 border-0">5%</button>
                    <button class="btn btn-lg btn-light col m-2 border-0">10%</button>
                    <button class="btn btn-lg btn-light col m-2 border-0">15%</button>
                </div>
                <div class="row p-3">
                    <button class="btn btn-lg btn-light col m-2 border-0">20%</button>
                    <button class="btn btn-lg btn-light col m-2 border-0">25%</button>
                    <button class="btn btn-lg btn-light col m-2 border-0">30%</button>
                </div>
                <div class="row p-3">
                    <button class="btn btn-lg btn-light col m-2 border-0">35%</button>
                    <button class="btn btn-lg btn-light col m-2 border-0">40%</button>
                    <button class="btn btn-lg btn-light col m-2 border-0">45%</button>
                </div>
            </div>
            <div class="col mt-1 justify-content-center text-center align-content-center">
                <a href="/">
                    <img src="/static/images/home.png" alt="Home" class="img-fluid" style="width:40px;" />
                </a>
                <a href="/CSs">
                    <img src="/static/images/cs.png" alt="Home" class="img-fluid" style="width:40px;" />
                </a>
            </div>
        </div>
    </div>

    <script>
        const socket = io();

    </script>
</body>

</html>

EVapp/templates/oldTemp/chat.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Private Chat</title>
    <script src="https://cdn.socket.io/4.6.0/socket.io.min.js"
        integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <style>
        ul {
            height: 300px;
            overflow-y: scroll;
            list-style: none;
            padding: 0;
        }

        li {
            padding: 5px;
            border-bottom: 1px solid #ddd;
        }

        input {
            width: 100%;
        }
    </style>
</head>

<body>
    <div style="height: 3rem;"></div>
    <div id="chatbox" class="container-fluid row justify-content-center align-content-center ">
        <div class="col-6  m-5 p-3 shadow-lg"
            style="width: 38rem; border-radius: 25px; border-color: transparent; background-color: rgb(202, 240, 248);">
            <h2 class="mt-2 text-center">Chat with <span id="recipient">{{ username }}</span></h2>
            <ul id="chat-messages">
            </ul>
            <div class="input-group">
                <input type="text" id="message" class="form-control" placeholder="Type your Message">
            </div>
            <div class="d-flex bd-highlight mb-3 mt-3">
                <button class="me-auto p-2 bd-highlight btn btn-light" onclick="sendMsg()">Send</button>
                <a class="p-2 me-2 bd-highlight btn btn-success" onclick="goPublic()">Go Public</a>
                <button class="p-2 bd-highlight btn btn-light" onclick="goBack()">Back</button>
            </div>
        </div>
    </div>

    <script>
        const socket = io({ autoConnect: false });
        let recipient = "";
        let sender = "";

        document.addEventListener("DOMContentLoaded", function () {
            socket.connect();
            const rec = new URLSearchParams(window.location.search);
            recipient = rec.get("recipient");

            const sen = new URLSearchParams(window.location.search);
            sender = sen.get("sender");

            let h2 = document.getElementById("recipient");
            h2.innerHTML = recipient;
        })


        function goBack() {
            window.location.href = "/";
        }

        function goPublic() {
            window.location.href = `/public?sender=${sender}`;
        }

        function sendMsg() {
            let message = document.getElementById("message").value;
            socket.emit("private_message", { message: message, recipient: recipient, sender: sender });
            document.getElementById("message").value = "";
        }

        document.getElementById("message").addEventListener("keyup", function (event) {
            if (event.key == "Enter") {
                sendMsg();
            }
        })

        socket.on("private_chat", function (data) {
            let ul = document.getElementById("chat-messages");
            let li = document.createElement("li");
            li.appendChild(document.createTextNode(data["username"] + ": " + data["message"]));
            ul.appendChild(li);
            ul.scrolltop = ul.scrollHeight;
        });

    </script>
</body>

</html>

EVapp/templates/oldTemp/indexPrev.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask-SocketIO</title>
    <script src="https://cdn.socket.io/4.6.0/socket.io.min.js"
        integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-fluid row justify-content-center align-content-center">
        <div class="col-6  m-5 p-3" style="width: 38rem; border-radius: 25px; border-color: transparent;">
            <div id="landing">
                <div style="height: 10rem;"></div>
                <input class="row mt-5 form-control" type="text" id="username" placeholder="Username">
                <button class="row position-absolute top-50 start-50 mt-3 translate-middle btn btn-primary"
                    id="register">REGISTER</button>
            </div>

            <div id="connected_EVs" style="display:none;"
                class="container-fluid row justify-content-center align-content-center">
                <h3 class="p-4 pt-0 text-center">Connected EVs</h3>
                <div class="list-group p-4 pt-0" id="connectedEVs">
                </div>

                <a class="row position-absolute top-130 start-50 mt-3 translate-middle col-2 btn btn-primary"
                    id="public">Go public</a>
            </div>
        </div>
    </div>

    <script>
        const socket = io({ autoConnect: false });
        let username = "";
        let currentUser = "";

        function reg() {
            username = document.getElementById("username").value;
            currentUser = username;

            socket.connect();

            socket.on("connect", function () {
                socket.emit("user_join", username);
            })

            document.getElementById("connected_EVs").style.display = "block";
            document.getElementById("landing").style.display = "none";
        }

        document.getElementById("register").addEventListener("click", function () {
            reg();
        })

        document.getElementById("username").addEventListener("keyup", function (event) {
            if (event.key == "Enter") {
                reg();
            }
        })

        document.getElementById("public").addEventListener("click", function () {
            window.location.href = `/public?sender=${currentUser}`;
        });


        socket.on("update_users", function (userList) {
            let listGroup = document.getElementById("connectedEVs");
            listGroup.innerHTML = "";

            userList.forEach(function (user) {
                let newItem = document.createElement("a");
                newItem.className = "list-group-item list-group-item-action";
                newItem.textContent = user;

                newItem.addEventListener("click", function () {
                    window.location.href = `/chat?recipient=${user}&sender=${currentUser}`;
                });

                listGroup.appendChild(newItem);
            })
        })


    </script>
</body>

</html>